Add bytes a support
LimeChain/as-scale-codec pull request #18
Opened 2020-05-13 12:23 UTC by bakasura980

2020-05-15 09:04 UTC, Daniel-K-Ivanov requested changes

2020-05-15 09:04 UTC, Daniel-K-Ivanov commented on assembly/ByteArray.ts
> +
Add inline documentation

2020-05-15 09:04 UTC, Daniel-K-Ivanov commented on assembly/__tests__/ByteArray.spec.ts
> +        const TEST_DATA_VAL: Array<Array<u8>> = [
Can we refactor the test so that it is more obvious that the `element[0]` of the `TEST_DATA_VAL` is expected to be decoded to `TEST_DATA_OUT[0]` below? Maybe we can use objects instead of 2 separate arrays?

2020-05-15 09:04 UTC, Daniel-K-Ivanov commented on assembly/utils/Bytes.ts
> +        throw new Error("Small int: mode does not exists");
you can change the message to "Small int: mode is invalid". 
And btw.. can you add comment "//TODO" to the side because in AssemblyScript the exception handling try/catch is not recommended .. we might need to refactor the error later and use   `null` for errors

2020-05-15 09:04 UTC, Daniel-K-Ivanov commented on assembly/utils/Bytes.ts
> +    static decodeSmallInt (input: u8[], mode: u8): i64 {
I think that everytime we read directly the input from the index we need to check whether that element at that index exists first.

f.e `input[3]` -> It might throw that this index does not exist.

2020-05-15 09:04 UTC, Daniel-K-Ivanov commented on assembly/utils/Bytes.ts
> +    static decodeUint (input: u8[]): u64 {
Instead of using `mode <= 2` you can use the constants `mode <= BIT_LENGTH.INT_16` or down below instead to 
`byteLen == 4` you might as-well use the constant: `byteLen == BIT_LENGTH.INT_32`. Same thing for `8`.

2020-05-15 09:04 UTC, Daniel-K-Ivanov commented on assembly/utils/Bytes.ts
> +        const mode = input[0] & 3;
I think that we need to handle the use-cases in which there is no element at position `0`. Maybe we need to do a check beforehand?

2020-05-15 09:12 UTC, bakasura980 commented on assembly/__tests__/ByteArray.spec.ts
> +        const TEST_DATA_VAL: Array<Array<u8>> = [
Objects are not supported

2020-05-15 13:08 UTC, Daniel-K-Ivanov requested changes

2020-05-15 13:08 UTC, Daniel-K-Ivanov commented on assembly/__tests__/ByteArray.spec.ts
> -            [0x42, 0x15, 0x50, 0x1c, 0x37, 0x7e, 0xd8, 0x66, 0x98, 0x2e],
You have removed 2 tests that I have added. Could you please add them again.

2020-05-18 07:40 UTC, Daniel-K-Ivanov approved these changes

2020-05-18 07:40 UTC, merged